apiVersion: v1
kind: Namespace
metadata:
  name: uptimekuma
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptimekuma-pvc-storage
  namespace: uptimekuma
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptimekuma
  namespace: uptimekuma
spec:
  replicas: 1
  serviceName: uptimekuma-service
  selector:
    matchLabels:
      app: uptimekuma
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      containers:
        - name: uptimekuma
          image: louislam/uptime-kuma:latest
          env:
            - name: UPTIME_KUMA_PORT
              value: "3001"
            - name: PORT
              value: "3001"
          ports:
            - name: uptimekuma
              containerPort: 3001
              protocol: TCP
          volumeMounts:
            - name: uptimekuma-pvc-storage
              mountPath: /app/data

  volumeClaimTemplates:
    - metadata:
        name: uptimekuma-pvc-storage
      spec:
        accessModes: ["ReadWriteMany"]
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: uptimekuma-service
spec:
  selector:
    app: uptimekuma
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma
  namespace: uptimekuma
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  labels:
    app: uptimekuma
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - uptime.int.irontec.dev
      secretName: uptime.int.irontec.dev
  rules:
    - host: uptime.int.irontec.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptimekuma-service
                port:
                  number: 3001
